name: Bitcoin Data Scrapers

on:
  schedule:
    - cron: "*/10 * * * *"    # every 10 minutes
  workflow_dispatch:          # allows manual trigger from GitHub UI

jobs:
  run-scrapers:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York    # optional: sets timezone
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium pandas webdriver-manager fake-useragent

      - name: Run both scrapers
        run: |
          python bitcoin_scraper.py
          python bitcoin_scraper_optimized.py

      - name: Commit and push updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase
          git add .
          git commit -m "Automated data update" || echo "No changes"
          git push
